### PR TITLE
configure-data-sources.es.md

### PR DESCRIPTION
**Pull request by johnfelipe**
Pls review this collab for translate all documentation to spanish

### CODE REVIEW

**Comment by johnfelipe** [comment]
I have read the CLA Document and I hereby sign the CLA
recheck

**Comment by johnfelipe** [comment]
why not merge?

**Comment by johnfelipe** [comment]
I have read the CLA Document and I hereby sign the CLA
recheck

**Comment by johnfelipe** [comment]
Why not merge?

**Comment by Redjaw** [comment]
recheck

**Pull request closed without merging**
